// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    org_id, name, description, type, category_id, type_id, department_id, owner_id, criticality, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, type, description, created_at, updated_at, org_id, category_id, type_id, department_id, criticality, confidentiality, integrity, availability, status, location, lifecycle_stage, compliance_status, ip_address, serial_number, purchase_date, warranty_expiry, owner_id
`

type CreateAssetParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Type         string      `json:"type"`
	CategoryID   pgtype.UUID `json:"category_id"`
	TypeID       pgtype.UUID `json:"type_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Criticality  string      `json:"criticality"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.CategoryID,
		arg.TypeID,
		arg.DepartmentID,
		arg.OwnerID,
		arg.Criticality,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.CategoryID,
		&i.TypeID,
		&i.DepartmentID,
		&i.Criticality,
		&i.Confidentiality,
		&i.Integrity,
		&i.Availability,
		&i.Status,
		&i.Location,
		&i.LifecycleStage,
		&i.ComplianceStatus,
		&i.IpAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.OwnerID,
	)
	return i, err
}

const createAssetControl = `-- name: CreateAssetControl :one
INSERT INTO asset_controls (
    asset_id, control_id, implementation_notes, coverage_status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, asset_id, control_id, coverage_status, implementation_notes, last_reviewed_at, created_at, updated_at, org_id
`

type CreateAssetControlParams struct {
	AssetID             pgtype.UUID `json:"asset_id"`
	ControlID           pgtype.UUID `json:"control_id"`
	ImplementationNotes pgtype.Text `json:"implementation_notes"`
	CoverageStatus      pgtype.Text `json:"coverage_status"`
}

func (q *Queries) CreateAssetControl(ctx context.Context, arg CreateAssetControlParams) (AssetControl, error) {
	row := q.db.QueryRow(ctx, createAssetControl,
		arg.AssetID,
		arg.ControlID,
		arg.ImplementationNotes,
		arg.CoverageStatus,
	)
	var i AssetControl
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ControlID,
		&i.CoverageStatus,
		&i.ImplementationNotes,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const deleteAssetControl = `-- name: DeleteAssetControl :exec
DELETE FROM asset_controls
WHERE asset_id = $1 AND control_id = $2
`

type DeleteAssetControlParams struct {
	AssetID   pgtype.UUID `json:"asset_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

func (q *Queries) DeleteAssetControl(ctx context.Context, arg DeleteAssetControlParams) error {
	_, err := q.db.Exec(ctx, deleteAssetControl, arg.AssetID, arg.ControlID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, type, description, created_at, updated_at, org_id, category_id, type_id, department_id, criticality, confidentiality, integrity, availability, status, location, lifecycle_stage, compliance_status, ip_address, serial_number, purchase_date, warranty_expiry, owner_id FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.CategoryID,
		&i.TypeID,
		&i.DepartmentID,
		&i.Criticality,
		&i.Confidentiality,
		&i.Integrity,
		&i.Availability,
		&i.Status,
		&i.Location,
		&i.LifecycleStage,
		&i.ComplianceStatus,
		&i.IpAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.OwnerID,
	)
	return i, err
}

const listAssetCategories = `-- name: ListAssetCategories :many
SELECT id, org_id, name, description FROM asset_categories ORDER BY name
`

func (q *Queries) ListAssetCategories(ctx context.Context) ([]AssetCategory, error) {
	rows, err := q.db.Query(ctx, listAssetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetCategory
	for rows.Next() {
		var i AssetCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetTypes = `-- name: ListAssetTypes :many
SELECT id, org_id, name, category_id, description FROM asset_types ORDER BY name
`

func (q *Queries) ListAssetTypes(ctx context.Context) ([]AssetType, error) {
	rows, err := q.db.Query(ctx, listAssetTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetType
	for rows.Next() {
		var i AssetType
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CategoryID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, type, description, created_at, updated_at, org_id, category_id, type_id, department_id, criticality, confidentiality, integrity, availability, status, location, lifecycle_stage, compliance_status, ip_address, serial_number, purchase_date, warranty_expiry, owner_id FROM assets
ORDER BY name ASC
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.CategoryID,
			&i.TypeID,
			&i.DepartmentID,
			&i.Criticality,
			&i.Confidentiality,
			&i.Integrity,
			&i.Availability,
			&i.Status,
			&i.Location,
			&i.LifecycleStage,
			&i.ComplianceStatus,
			&i.IpAddress,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.WarrantyExpiry,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlAssets = `-- name: ListControlAssets :many
SELECT a.id, a.name, a.type, a.description, a.created_at, a.updated_at, a.org_id, a.category_id, a.type_id, a.department_id, a.criticality, a.confidentiality, a.integrity, a.availability, a.status, a.location, a.lifecycle_stage, a.compliance_status, a.ip_address, a.serial_number, a.purchase_date, a.warranty_expiry, a.owner_id, ac.implementation_notes, ac.coverage_status, ac.created_at as mapping_created_at
FROM assets a
JOIN asset_controls ac ON a.id = ac.asset_id
WHERE ac.control_id = $1
`

type ListControlAssetsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OrgID               pgtype.UUID        `json:"org_id"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	TypeID              pgtype.UUID        `json:"type_id"`
	DepartmentID        pgtype.UUID        `json:"department_id"`
	Criticality         string             `json:"criticality"`
	Confidentiality     int32              `json:"confidentiality"`
	Integrity           int32              `json:"integrity"`
	Availability        int32              `json:"availability"`
	Status              string             `json:"status"`
	Location            pgtype.Text        `json:"location"`
	LifecycleStage      pgtype.Text        `json:"lifecycle_stage"`
	ComplianceStatus    pgtype.Text        `json:"compliance_status"`
	IpAddress           pgtype.Text        `json:"ip_address"`
	SerialNumber        pgtype.Text        `json:"serial_number"`
	PurchaseDate        pgtype.Date        `json:"purchase_date"`
	WarrantyExpiry      pgtype.Date        `json:"warranty_expiry"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	ImplementationNotes pgtype.Text        `json:"implementation_notes"`
	CoverageStatus      pgtype.Text        `json:"coverage_status"`
	MappingCreatedAt    pgtype.Timestamptz `json:"mapping_created_at"`
}

func (q *Queries) ListControlAssets(ctx context.Context, controlID pgtype.UUID) ([]ListControlAssetsRow, error) {
	rows, err := q.db.Query(ctx, listControlAssets, controlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlAssetsRow
	for rows.Next() {
		var i ListControlAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.CategoryID,
			&i.TypeID,
			&i.DepartmentID,
			&i.Criticality,
			&i.Confidentiality,
			&i.Integrity,
			&i.Availability,
			&i.Status,
			&i.Location,
			&i.LifecycleStage,
			&i.ComplianceStatus,
			&i.IpAddress,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.WarrantyExpiry,
			&i.OwnerID,
			&i.ImplementationNotes,
			&i.CoverageStatus,
			&i.MappingCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET 
    name = $2,
    description = $3,
    type = $4,
    category_id = $5,
    type_id = $6,
    department_id = $7,
    owner_id = $8,
    criticality = $9,
    status = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, description, created_at, updated_at, org_id, category_id, type_id, department_id, criticality, confidentiality, integrity, availability, status, location, lifecycle_stage, compliance_status, ip_address, serial_number, purchase_date, warranty_expiry, owner_id
`

type UpdateAssetParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Type         string      `json:"type"`
	CategoryID   pgtype.UUID `json:"category_id"`
	TypeID       pgtype.UUID `json:"type_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Criticality  string      `json:"criticality"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.CategoryID,
		arg.TypeID,
		arg.DepartmentID,
		arg.OwnerID,
		arg.Criticality,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.CategoryID,
		&i.TypeID,
		&i.DepartmentID,
		&i.Criticality,
		&i.Confidentiality,
		&i.Integrity,
		&i.Availability,
		&i.Status,
		&i.Location,
		&i.LifecycleStage,
		&i.ComplianceStatus,
		&i.IpAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.OwnerID,
	)
	return i, err
}
