// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id,
    org_id,
    event_type,
    event_data,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, org_id, event_type, event_data, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	UserID    pgtype.Int8 `json:"user_id"`
	OrgID     pgtype.UUID `json:"org_id"`
	EventType string      `json:"event_type"`
	EventData []byte      `json:"event_data"`
	IpAddress pgtype.Text `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.OrgID,
		arg.EventType,
		arg.EventData,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.EventType,
		&i.EventData,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_logs
WHERE created_at < NOW() - ($1::int * INTERVAL '1 day')
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, dollar_1 int32) error {
	_, err := q.db.Exec(ctx, deleteOldAuditLogs, dollar_1)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, user_id, org_id, event_type, event_data, ip_address, user_agent, created_at FROM audit_logs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuditLog(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.EventType,
		&i.EventData,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, org_id, event_type, event_data, ip_address, user_agent, created_at FROM audit_logs
WHERE 
    (user_id = $3 OR $3 IS NULL) AND
    (org_id = $4 OR $4 IS NULL) AND
    (event_type = $5 OR $5 IS NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	UserID    pgtype.Int8 `json:"user_id"`
	OrgID     pgtype.UUID `json:"org_id"`
	EventType pgtype.Text `json:"event_type"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.OrgID,
		arg.EventType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.EventType,
			&i.EventData,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
