// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
  name, description, head_user_id, org_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, description, created_at, updated_at, org_id, head_user_id, parent_id, email
`

type CreateDepartmentParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	HeadUserID  pgtype.UUID `json:"head_user_id"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.Name,
		arg.Description,
		arg.HeadUserID,
		arg.OrgID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.HeadUserID,
		&i.ParentID,
		&i.Email,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, description, created_at, updated_at, org_id, head_user_id, parent_id, email FROM departments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.HeadUserID,
		&i.ParentID,
		&i.Email,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, description, created_at, updated_at, org_id, head_user_id, parent_id, email FROM departments
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.HeadUserID,
			&i.ParentID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
