// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frameworks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createControl = `-- name: CreateControl :one
INSERT INTO controls (
  org_id, code, title, description, category
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, code, title, description, category, created_at, updated_at, org_id, owner_id, department_id, domain_id
`

type CreateControlParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Code        string      `json:"code"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
}

func (q *Queries) CreateControl(ctx context.Context, arg CreateControlParams) (Control, error) {
	row := q.db.QueryRow(ctx, createControl,
		arg.OrgID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Control
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.OwnerID,
		&i.DepartmentID,
		&i.DomainID,
	)
	return i, err
}

const createControlEvidence = `-- name: CreateControlEvidence :one
INSERT INTO control_evidence (
    control_id, name, description, evidence_type, file_name, file_path, external_url, checksum
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, control_id, name, description, evidence_type, file_name, file_path, file_size, mime_type, external_url, checksum, collected_at, is_valid, created_at, updated_at
`

type CreateControlEvidenceParams struct {
	ControlID    pgtype.UUID `json:"control_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	EvidenceType string      `json:"evidence_type"`
	FileName     pgtype.Text `json:"file_name"`
	FilePath     pgtype.Text `json:"file_path"`
	ExternalUrl  pgtype.Text `json:"external_url"`
	Checksum     pgtype.Text `json:"checksum"`
}

func (q *Queries) CreateControlEvidence(ctx context.Context, arg CreateControlEvidenceParams) (ControlEvidence, error) {
	row := q.db.QueryRow(ctx, createControlEvidence,
		arg.ControlID,
		arg.Name,
		arg.Description,
		arg.EvidenceType,
		arg.FileName,
		arg.FilePath,
		arg.ExternalUrl,
		arg.Checksum,
	)
	var i ControlEvidence
	err := row.Scan(
		&i.ID,
		&i.ControlID,
		&i.Name,
		&i.Description,
		&i.EvidenceType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.ExternalUrl,
		&i.Checksum,
		&i.CollectedAt,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFramework = `-- name: CreateFramework :one
INSERT INTO frameworks (
  name, description, version, status, org_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, description, version, status, control_count, created_at, updated_at, org_id
`

type CreateFrameworkParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Version     pgtype.Text `json:"version"`
	Status      string      `json:"status"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateFramework(ctx context.Context, arg CreateFrameworkParams) (Framework, error) {
	row := q.db.QueryRow(ctx, createFramework,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Status,
		arg.OrgID,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Status,
		&i.ControlCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const deleteControl = `-- name: DeleteControl :exec
DELETE FROM controls WHERE id = $1
`

func (q *Queries) DeleteControl(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteControl, id)
	return err
}

const deleteFramework = `-- name: DeleteFramework :exec
DELETE FROM frameworks
WHERE id = $1 AND org_id = $2
`

type DeleteFrameworkParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteFramework(ctx context.Context, arg DeleteFrameworkParams) error {
	_, err := q.db.Exec(ctx, deleteFramework, arg.ID, arg.OrgID)
	return err
}

const getControl = `-- name: GetControl :one
SELECT 
    c.id, c.code, c.title, c.description, c.category, c.created_at, c.updated_at, c.org_id, c.owner_id, c.department_id, c.domain_id,
    cd.name as domain_name,
    p.full_name as owner_name,
    p.email as owner_email,
    p.avatar_url as owner_avatar_url,
    COALESCE(
        (SELECT STRING_AGG(f.name, ', ') FROM framework_controls fc
         JOIN frameworks f ON f.id = fc.framework_id
         WHERE fc.control_id = c.id),
        ''
    ) as framework_names,
    (SELECT COUNT(*) FROM framework_controls fc WHERE fc.control_id = c.id) as framework_count,
    (SELECT COUNT(*) FROM asset_controls ac WHERE ac.control_id = c.id) as asset_count,
    (SELECT COUNT(*) FROM risk_controls rc WHERE rc.control_id = c.id) as risk_count,
    COALESCE(
        (SELECT MAX(r.inherent_impact * r.inherent_likelihood) 
         FROM risk_controls rc 
         JOIN risks r ON r.id = rc.risk_id 
         WHERE rc.control_id = c.id), 
        0
    )::int as max_risk_score
FROM controls c
LEFT JOIN control_domains cd ON c.domain_id = cd.id
LEFT JOIN profiles p ON c.owner_id = p.id
WHERE c.id = $1
`

type GetControlRow struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Category       pgtype.Text        `json:"category"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgID          pgtype.UUID        `json:"org_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	DomainID       pgtype.UUID        `json:"domain_id"`
	DomainName     pgtype.Text        `json:"domain_name"`
	OwnerName      pgtype.Text        `json:"owner_name"`
	OwnerEmail     pgtype.Text        `json:"owner_email"`
	OwnerAvatarUrl pgtype.Text        `json:"owner_avatar_url"`
	FrameworkNames interface{}        `json:"framework_names"`
	FrameworkCount int64              `json:"framework_count"`
	AssetCount     int64              `json:"asset_count"`
	RiskCount      int64              `json:"risk_count"`
	MaxRiskScore   int32              `json:"max_risk_score"`
}

func (q *Queries) GetControl(ctx context.Context, id pgtype.UUID) (GetControlRow, error) {
	row := q.db.QueryRow(ctx, getControl, id)
	var i GetControlRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.OwnerID,
		&i.DepartmentID,
		&i.DomainID,
		&i.DomainName,
		&i.OwnerName,
		&i.OwnerEmail,
		&i.OwnerAvatarUrl,
		&i.FrameworkNames,
		&i.FrameworkCount,
		&i.AssetCount,
		&i.RiskCount,
		&i.MaxRiskScore,
	)
	return i, err
}

const getControlStats = `-- name: GetControlStats :one
SELECT
  COUNT(*)::bigint as total_controls,
  COUNT(*) FILTER (WHERE c.category IS NOT NULL AND c.category != '')::bigint as active_controls,
  COUNT(*) FILTER (WHERE c.category IS NULL OR c.category = '')::bigint as draft_controls,
  (SELECT COUNT(DISTINCT fc.control_id)::bigint FROM framework_controls fc JOIN controls c2 ON c2.id = fc.control_id WHERE c2.org_id = $1) as mapped_controls,
  COUNT(DISTINCT c.category) FILTER (WHERE c.category IS NOT NULL AND c.category != '')::bigint as unique_categories
FROM controls c
WHERE c.org_id = $1
`

type GetControlStatsRow struct {
	TotalControls    int64 `json:"total_controls"`
	ActiveControls   int64 `json:"active_controls"`
	DraftControls    int64 `json:"draft_controls"`
	MappedControls   int64 `json:"mapped_controls"`
	UniqueCategories int64 `json:"unique_categories"`
}

func (q *Queries) GetControlStats(ctx context.Context, orgID pgtype.UUID) (GetControlStatsRow, error) {
	row := q.db.QueryRow(ctx, getControlStats, orgID)
	var i GetControlStatsRow
	err := row.Scan(
		&i.TotalControls,
		&i.ActiveControls,
		&i.DraftControls,
		&i.MappedControls,
		&i.UniqueCategories,
	)
	return i, err
}

const getFramework = `-- name: GetFramework :one
SELECT 
    f.id, f.name, f.description, f.version, f.status, f.control_count, f.created_at, f.updated_at, f.org_id,
    (SELECT COUNT(*) FROM framework_controls fc WHERE fc.framework_id = f.id) as control_count,
    (
        SELECT COALESCE(ROUND(COUNT(DISTINCT tc.control_id)::FLOAT / NULLIF(COUNT(DISTINCT fc.control_id), 0) * 100), 0)
        FROM framework_controls fc
        LEFT JOIN (
            SELECT DISTINCT control_id 
            FROM tasks 
            WHERE status = 'completed' AND result = 'compliant'
        ) tc ON fc.control_id = tc.control_id
        WHERE fc.framework_id = f.id
    ) as progress
FROM frameworks f
WHERE f.id = $1 AND f.org_id = $2 LIMIT 1
`

type GetFrameworkParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

type GetFrameworkRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Version        pgtype.Text        `json:"version"`
	Status         string             `json:"status"`
	ControlCount   pgtype.Int4        `json:"control_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgID          pgtype.UUID        `json:"org_id"`
	ControlCount_2 int64              `json:"control_count_2"`
	Progress       interface{}        `json:"progress"`
}

func (q *Queries) GetFramework(ctx context.Context, arg GetFrameworkParams) (GetFrameworkRow, error) {
	row := q.db.QueryRow(ctx, getFramework, arg.ID, arg.OrgID)
	var i GetFrameworkRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Status,
		&i.ControlCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.ControlCount_2,
		&i.Progress,
	)
	return i, err
}

const listAllControls = `-- name: ListAllControls :many
SELECT c.id, c.code, c.title, c.description, c.category, c.created_at, c.updated_at, c.org_id, c.owner_id, c.department_id, c.domain_id,
       COALESCE(
         (SELECT STRING_AGG(f.name, ', ') FROM framework_controls fc
          JOIN frameworks f ON f.id = fc.framework_id
          WHERE fc.control_id = c.id),
         ''
       ) as framework_names,
       (SELECT COUNT(*) FROM framework_controls fc WHERE fc.control_id = c.id) as framework_count
FROM controls c
WHERE c.org_id = $1
ORDER BY c.code
`

type ListAllControlsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Category       pgtype.Text        `json:"category"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgID          pgtype.UUID        `json:"org_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	DomainID       pgtype.UUID        `json:"domain_id"`
	FrameworkNames interface{}        `json:"framework_names"`
	FrameworkCount int64              `json:"framework_count"`
}

func (q *Queries) ListAllControls(ctx context.Context, orgID pgtype.UUID) ([]ListAllControlsRow, error) {
	rows, err := q.db.Query(ctx, listAllControls, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllControlsRow
	for rows.Next() {
		var i ListAllControlsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.OwnerID,
			&i.DepartmentID,
			&i.DomainID,
			&i.FrameworkNames,
			&i.FrameworkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableControls = `-- name: ListAvailableControls :many
SELECT c.id, c.code, c.title, c.description, c.category, c.created_at, c.updated_at, c.org_id, c.owner_id, c.department_id, c.domain_id FROM controls c
WHERE c.org_id = $1 AND c.id NOT IN (
    SELECT control_id FROM framework_controls WHERE framework_id = $2
)
ORDER BY c.code
`

type ListAvailableControlsParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	FrameworkID pgtype.UUID `json:"framework_id"`
}

// Controls not yet mapped to this specific framework
func (q *Queries) ListAvailableControls(ctx context.Context, arg ListAvailableControlsParams) ([]Control, error) {
	rows, err := q.db.Query(ctx, listAvailableControls, arg.OrgID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Control
	for rows.Next() {
		var i Control
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.OwnerID,
			&i.DepartmentID,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlEvidence = `-- name: ListControlEvidence :many
SELECT id, control_id, name, description, evidence_type, file_name, file_path, file_size, mime_type, external_url, checksum, collected_at, is_valid, created_at, updated_at FROM control_evidence
WHERE control_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListControlEvidence(ctx context.Context, controlID pgtype.UUID) ([]ControlEvidence, error) {
	rows, err := q.db.Query(ctx, listControlEvidence, controlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlEvidence
	for rows.Next() {
		var i ControlEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ControlID,
			&i.Name,
			&i.Description,
			&i.EvidenceType,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.ExternalUrl,
			&i.Checksum,
			&i.CollectedAt,
			&i.IsValid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlTasks = `-- name: ListControlTasks :many
SELECT t.id, t.program_id, t.control_id, t.asset_id, t.owner_id, t.reviewer_id, t.assessor_id, t.title, t.description, t.status, t.result, t.due_date, t.created_at, t.updated_at, t.org_id, t.notes, t.reviewer_notes, t.assessor_notes, t.visible_to_assignee, t.task_type, t.evidence_required, p.name as program_name
FROM tasks t
LEFT JOIN programs p ON t.program_id = p.id
WHERE t.control_id = $1
ORDER BY t.created_at DESC
LIMIT 10
`

type ListControlTasksRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProgramID         pgtype.UUID        `json:"program_id"`
	ControlID         pgtype.UUID        `json:"control_id"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	AssessorID        pgtype.UUID        `json:"assessor_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Status            string             `json:"status"`
	Result            pgtype.Text        `json:"result"`
	DueDate           pgtype.Date        `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OrgID             pgtype.UUID        `json:"org_id"`
	Notes             pgtype.Text        `json:"notes"`
	ReviewerNotes     pgtype.Text        `json:"reviewer_notes"`
	AssessorNotes     pgtype.Text        `json:"assessor_notes"`
	VisibleToAssignee pgtype.Bool        `json:"visible_to_assignee"`
	TaskType          pgtype.Text        `json:"task_type"`
	EvidenceRequired  []byte             `json:"evidence_required"`
	ProgramName       pgtype.Text        `json:"program_name"`
}

func (q *Queries) ListControlTasks(ctx context.Context, controlID pgtype.UUID) ([]ListControlTasksRow, error) {
	rows, err := q.db.Query(ctx, listControlTasks, controlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlTasksRow
	for rows.Next() {
		var i ListControlTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ControlID,
			&i.AssetID,
			&i.OwnerID,
			&i.ReviewerID,
			&i.AssessorID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Result,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.Notes,
			&i.ReviewerNotes,
			&i.AssessorNotes,
			&i.VisibleToAssignee,
			&i.TaskType,
			&i.EvidenceRequired,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlsByAsset = `-- name: ListControlsByAsset :many
SELECT c.id, c.code, c.title, c.description, c.category, c.created_at, c.updated_at, c.org_id, c.owner_id, c.department_id, c.domain_id, ac.coverage_status 
FROM controls c
JOIN asset_controls ac ON c.id = ac.control_id
WHERE ac.asset_id = $1
`

type ListControlsByAssetRow struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Category       pgtype.Text        `json:"category"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgID          pgtype.UUID        `json:"org_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	DomainID       pgtype.UUID        `json:"domain_id"`
	CoverageStatus pgtype.Text        `json:"coverage_status"`
}

func (q *Queries) ListControlsByAsset(ctx context.Context, assetID pgtype.UUID) ([]ListControlsByAssetRow, error) {
	rows, err := q.db.Query(ctx, listControlsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlsByAssetRow
	for rows.Next() {
		var i ListControlsByAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.OwnerID,
			&i.DepartmentID,
			&i.DomainID,
			&i.CoverageStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlsByFramework = `-- name: ListControlsByFramework :many
SELECT c.id, c.code, c.title, c.description, c.category, c.created_at, c.updated_at, c.org_id, c.owner_id, c.department_id, c.domain_id FROM controls c
JOIN framework_controls fc ON c.id = fc.control_id
WHERE fc.framework_id = $1
ORDER BY c.code
`

func (q *Queries) ListControlsByFramework(ctx context.Context, frameworkID pgtype.UUID) ([]Control, error) {
	rows, err := q.db.Query(ctx, listControlsByFramework, frameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Control
	for rows.Next() {
		var i Control
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.OwnerID,
			&i.DepartmentID,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworks = `-- name: ListFrameworks :many
SELECT 
    f.id, f.name, f.description, f.version, f.status, f.control_count, f.created_at, f.updated_at, f.org_id,
    (SELECT COUNT(*) FROM framework_controls fc WHERE fc.framework_id = f.id) as control_count,
    (
        SELECT COALESCE(ROUND(COUNT(DISTINCT tc.control_id)::FLOAT / NULLIF(COUNT(DISTINCT fc.control_id), 0) * 100), 0)
        FROM framework_controls fc
        LEFT JOIN (
            SELECT DISTINCT control_id 
            FROM tasks 
            WHERE status = 'completed' AND result = 'compliant'
        ) tc ON fc.control_id = tc.control_id
        WHERE fc.framework_id = f.id
    ) as progress
FROM frameworks f
WHERE f.org_id = $1
ORDER BY f.name
`

type ListFrameworksRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Version        pgtype.Text        `json:"version"`
	Status         string             `json:"status"`
	ControlCount   pgtype.Int4        `json:"control_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgID          pgtype.UUID        `json:"org_id"`
	ControlCount_2 int64              `json:"control_count_2"`
	Progress       interface{}        `json:"progress"`
}

func (q *Queries) ListFrameworks(ctx context.Context, orgID pgtype.UUID) ([]ListFrameworksRow, error) {
	rows, err := q.db.Query(ctx, listFrameworks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrameworksRow
	for rows.Next() {
		var i ListFrameworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Status,
			&i.ControlCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.ControlCount_2,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapAssetControl = `-- name: MapAssetControl :one
INSERT INTO asset_controls (
  asset_id, control_id, coverage_status, implementation_notes
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, asset_id, control_id, coverage_status, implementation_notes, last_reviewed_at, created_at, updated_at
`

type MapAssetControlParams struct {
	AssetID             pgtype.UUID `json:"asset_id"`
	ControlID           pgtype.UUID `json:"control_id"`
	CoverageStatus      pgtype.Text `json:"coverage_status"`
	ImplementationNotes pgtype.Text `json:"implementation_notes"`
}

func (q *Queries) MapAssetControl(ctx context.Context, arg MapAssetControlParams) (AssetControl, error) {
	row := q.db.QueryRow(ctx, mapAssetControl,
		arg.AssetID,
		arg.ControlID,
		arg.CoverageStatus,
		arg.ImplementationNotes,
	)
	var i AssetControl
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ControlID,
		&i.CoverageStatus,
		&i.ImplementationNotes,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mapControl = `-- name: MapControl :one
INSERT INTO framework_controls (
  framework_id, control_id
) VALUES (
  $1, $2
)
RETURNING framework_id, control_id, created_at
`

type MapControlParams struct {
	FrameworkID pgtype.UUID `json:"framework_id"`
	ControlID   pgtype.UUID `json:"control_id"`
}

func (q *Queries) MapControl(ctx context.Context, arg MapControlParams) (FrameworkControl, error) {
	row := q.db.QueryRow(ctx, mapControl, arg.FrameworkID, arg.ControlID)
	var i FrameworkControl
	err := row.Scan(&i.FrameworkID, &i.ControlID, &i.CreatedAt)
	return i, err
}

const unmapControl = `-- name: UnmapControl :exec
DELETE FROM framework_controls
WHERE framework_id = $1 AND control_id = $2
`

type UnmapControlParams struct {
	FrameworkID pgtype.UUID `json:"framework_id"`
	ControlID   pgtype.UUID `json:"control_id"`
}

func (q *Queries) UnmapControl(ctx context.Context, arg UnmapControlParams) error {
	_, err := q.db.Exec(ctx, unmapControl, arg.FrameworkID, arg.ControlID)
	return err
}

const updateControl = `-- name: UpdateControl :one
UPDATE controls
SET title = $2, description = $3, category = $4, code = $5, updated_at = CURRENT_TIMESTAMP, 
    owner_id = $6, department_id = $7, domain_id = $8
WHERE id = $1
RETURNING id, code, title, description, category, created_at, updated_at, org_id, owner_id, department_id, domain_id
`

type UpdateControlParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Category     pgtype.Text `json:"category"`
	Code         string      `json:"code"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	DomainID     pgtype.UUID `json:"domain_id"`
}

func (q *Queries) UpdateControl(ctx context.Context, arg UpdateControlParams) (Control, error) {
	row := q.db.QueryRow(ctx, updateControl,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Code,
		arg.OwnerID,
		arg.DepartmentID,
		arg.DomainID,
	)
	var i Control
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.OwnerID,
		&i.DepartmentID,
		&i.DomainID,
	)
	return i, err
}

const updateFramework = `-- name: UpdateFramework :one
UPDATE frameworks
SET name = $2, description = $3, version = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $5
RETURNING id, name, description, version, status, control_count, created_at, updated_at, org_id
`

type UpdateFrameworkParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Version     pgtype.Text `json:"version"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateFramework(ctx context.Context, arg UpdateFrameworkParams) (Framework, error) {
	row := q.db.QueryRow(ctx, updateFramework,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.OrgID,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Status,
		&i.ControlCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const updateFrameworkStatus = `-- name: UpdateFrameworkStatus :one
UPDATE frameworks
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $3
RETURNING id, name, description, version, status, control_count, created_at, updated_at, org_id
`

type UpdateFrameworkStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateFrameworkStatus(ctx context.Context, arg UpdateFrameworkStatusParams) (Framework, error) {
	row := q.db.QueryRow(ctx, updateFrameworkStatus, arg.ID, arg.Status, arg.OrgID)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Status,
		&i.ControlCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const upsertControl = `-- name: UpsertControl :one
INSERT INTO controls (
  org_id, code, title, description, category
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (org_id, code) DO UPDATE
SET 
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, code, title, description, category, created_at, updated_at, org_id, owner_id, department_id, domain_id
`

type UpsertControlParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Code        string      `json:"code"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
}

func (q *Queries) UpsertControl(ctx context.Context, arg UpsertControlParams) (Control, error) {
	row := q.db.QueryRow(ctx, upsertControl,
		arg.OrgID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Control
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.OwnerID,
		&i.DepartmentID,
		&i.DomainID,
	)
	return i, err
}
