// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       int64              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SystemConfig struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Payload   []byte             `json:"payload"`
	Result    []byte             `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
}

type User struct {
	ID                         int64              `json:"id"`
	Username                   string             `json:"username"`
	Email                      string             `json:"email"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	PasswordHash               string             `json:"password_hash"`
	Role                       string             `json:"role"`
	EmailVerified              bool               `json:"email_verified"`
	VerificationToken          pgtype.Text        `json:"verification_token"`
	VerificationTokenExpiresAt pgtype.Timestamptz `json:"verification_token_expires_at"`
}
