// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    org_id,
    title,
    message,
    type,
    link
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, org_id, title, message, type, link, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  int64       `json:"user_id"`
	OrgID   pgtype.UUID `json:"org_id"`
	Title   string      `json:"title"`
	Message string      `json:"message"`
	Type    string      `json:"type"`
	Link    pgtype.Text `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.OrgID,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Link,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND org_id = $2 AND is_read = false
`

type GetUnreadCountParams struct {
	UserID int64       `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.UserID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, org_id, title, message, type, link, is_read, created_at FROM notifications
WHERE user_id = $1 AND org_id = $2
ORDER BY created_at DESC
`

type ListNotificationsByUserParams struct {
	UserID int64       `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND org_id = $2 AND is_read = false
`

type MarkAllAsReadParams struct {
	UserID int64       `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) MarkAllAsRead(ctx context.Context, arg MarkAllAsReadParams) error {
	_, err := q.db.Exec(ctx, markAllAsRead, arg.UserID, arg.OrgID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, org_id, title, message, type, link, is_read, created_at
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Link,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
