// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFrameworkToProgram = `-- name: AddFrameworkToProgram :one
INSERT INTO program_frameworks (
  program_id, framework_id
) VALUES (
  $1, $2
)
RETURNING id, program_id, framework_id, created_at
`

type AddFrameworkToProgramParams struct {
	ProgramID   pgtype.UUID `json:"program_id"`
	FrameworkID pgtype.UUID `json:"framework_id"`
}

func (q *Queries) AddFrameworkToProgram(ctx context.Context, arg AddFrameworkToProgramParams) (ProgramFramework, error) {
	row := q.db.QueryRow(ctx, addFrameworkToProgram, arg.ProgramID, arg.FrameworkID)
	var i ProgramFramework
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.FrameworkID,
		&i.CreatedAt,
	)
	return i, err
}

const addScopeToProgram = `-- name: AddScopeToProgram :one
INSERT INTO program_scope (
  program_id, resource_id, resource_type
) VALUES (
  $1, $2, $3
)
RETURNING id, program_id, resource_type, resource_id, created_at
`

type AddScopeToProgramParams struct {
	ProgramID    pgtype.UUID `json:"program_id"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	ResourceType string      `json:"resource_type"`
}

func (q *Queries) AddScopeToProgram(ctx context.Context, arg AddScopeToProgramParams) (ProgramScope, error) {
	row := q.db.QueryRow(ctx, addScopeToProgram, arg.ProgramID, arg.ResourceID, arg.ResourceType)
	var i ProgramScope
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (
  name, description, type, status, start_date, end_date, progress, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, description, type, status, start_date, end_date, progress, created_by, created_at, updated_at
`

type CreateProgramParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Progress    pgtype.Int4        `json:"progress"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Progress,
		arg.CreatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Progress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, name, description, type, status, start_date, end_date, progress, created_by, created_at, updated_at FROM programs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProgram(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Progress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, name, description, type, status, start_date, end_date, progress, created_by, created_at, updated_at FROM programs
ORDER BY start_date DESC
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Progress,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
