// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithVerification(ctx context.Context, arg CreateUserWithVerificationParams) (User, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSystemConfig(ctx context.Context, key string) (SystemConfig, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (User, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListTasksByOrg(ctx context.Context, orgID pgtype.UUID) ([]Task, error)
	ListUsersByOrg(ctx context.Context, orgID pgtype.UUID) ([]User, error)
	SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) (SystemConfig, error)
	UpdateSessionBlock(ctx context.Context, arg UpdateSessionBlockParams) (Session, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error)
	VerifyUserEmail(ctx context.Context, verificationToken pgtype.Text) (User, error)
}

var _ Querier = (*Queries)(nil)
