// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: risks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRisk = `-- name: CreateRisk :one
INSERT INTO risks (
    org_id, title, description, inherent_impact, inherent_likelihood, status, owner_id, 
    category, response_strategy, mitigation_plan, review_date, source_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, org_id, title, description, inherent_impact, inherent_likelihood, residual_impact, residual_likelihood, status, treatment_plan, owner_id, source_task_id, created_at, updated_at, category, response_strategy, mitigation_plan, review_date
`

type CreateRiskParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	InherentImpact     int32       `json:"inherent_impact"`
	InherentLikelihood int32       `json:"inherent_likelihood"`
	Status             string      `json:"status"`
	OwnerID            pgtype.UUID `json:"owner_id"`
	Category           pgtype.Text `json:"category"`
	ResponseStrategy   pgtype.Text `json:"response_strategy"`
	MitigationPlan     pgtype.Text `json:"mitigation_plan"`
	ReviewDate         pgtype.Date `json:"review_date"`
	SourceTaskID       pgtype.UUID `json:"source_task_id"`
}

func (q *Queries) CreateRisk(ctx context.Context, arg CreateRiskParams) (Risk, error) {
	row := q.db.QueryRow(ctx, createRisk,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.InherentImpact,
		arg.InherentLikelihood,
		arg.Status,
		arg.OwnerID,
		arg.Category,
		arg.ResponseStrategy,
		arg.MitigationPlan,
		arg.ReviewDate,
		arg.SourceTaskID,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.InherentImpact,
		&i.InherentLikelihood,
		&i.ResidualImpact,
		&i.ResidualLikelihood,
		&i.Status,
		&i.TreatmentPlan,
		&i.OwnerID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.ResponseStrategy,
		&i.MitigationPlan,
		&i.ReviewDate,
	)
	return i, err
}

const createRiskControl = `-- name: CreateRiskControl :one
INSERT INTO risk_controls (
    risk_id, control_id, notes, effectiveness
) VALUES (
    $1, $2, $3, $4
) RETURNING risk_id, control_id, effectiveness, notes, mapped_at
`

type CreateRiskControlParams struct {
	RiskID        pgtype.UUID `json:"risk_id"`
	ControlID     pgtype.UUID `json:"control_id"`
	Notes         pgtype.Text `json:"notes"`
	Effectiveness pgtype.Text `json:"effectiveness"`
}

func (q *Queries) CreateRiskControl(ctx context.Context, arg CreateRiskControlParams) (RiskControl, error) {
	row := q.db.QueryRow(ctx, createRiskControl,
		arg.RiskID,
		arg.ControlID,
		arg.Notes,
		arg.Effectiveness,
	)
	var i RiskControl
	err := row.Scan(
		&i.RiskID,
		&i.ControlID,
		&i.Effectiveness,
		&i.Notes,
		&i.MappedAt,
	)
	return i, err
}

const deleteRisk = `-- name: DeleteRisk :exec
DELETE FROM risks
WHERE id = $1
`

func (q *Queries) DeleteRisk(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRisk, id)
	return err
}

const deleteRiskControl = `-- name: DeleteRiskControl :exec
DELETE FROM risk_controls
WHERE risk_id = $1 AND control_id = $2
`

type DeleteRiskControlParams struct {
	RiskID    pgtype.UUID `json:"risk_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

func (q *Queries) DeleteRiskControl(ctx context.Context, arg DeleteRiskControlParams) error {
	_, err := q.db.Exec(ctx, deleteRiskControl, arg.RiskID, arg.ControlID)
	return err
}

const getRisk = `-- name: GetRisk :one
SELECT id, org_id, title, description, inherent_impact, inherent_likelihood, residual_impact, residual_likelihood, status, treatment_plan, owner_id, source_task_id, created_at, updated_at, category, response_strategy, mitigation_plan, review_date FROM risks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRisk(ctx context.Context, id pgtype.UUID) (Risk, error) {
	row := q.db.QueryRow(ctx, getRisk, id)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.InherentImpact,
		&i.InherentLikelihood,
		&i.ResidualImpact,
		&i.ResidualLikelihood,
		&i.Status,
		&i.TreatmentPlan,
		&i.OwnerID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.ResponseStrategy,
		&i.MitigationPlan,
		&i.ReviewDate,
	)
	return i, err
}

const linkRiskToControl = `-- name: LinkRiskToControl :exec
INSERT INTO risk_controls (risk_id, control_id, effectiveness, notes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (risk_id, control_id) DO UPDATE SET
    effectiveness = EXCLUDED.effectiveness,
    notes = EXCLUDED.notes
`

type LinkRiskToControlParams struct {
	RiskID        pgtype.UUID `json:"risk_id"`
	ControlID     pgtype.UUID `json:"control_id"`
	Effectiveness pgtype.Text `json:"effectiveness"`
	Notes         pgtype.Text `json:"notes"`
}

func (q *Queries) LinkRiskToControl(ctx context.Context, arg LinkRiskToControlParams) error {
	_, err := q.db.Exec(ctx, linkRiskToControl,
		arg.RiskID,
		arg.ControlID,
		arg.Effectiveness,
		arg.Notes,
	)
	return err
}

const listControlRisks = `-- name: ListControlRisks :many
SELECT r.id, r.org_id, r.title, r.description, r.inherent_impact, r.inherent_likelihood, r.residual_impact, r.residual_likelihood, r.status, r.treatment_plan, r.owner_id, r.source_task_id, r.created_at, r.updated_at, r.category, r.response_strategy, r.mitigation_plan, r.review_date, rc.notes, rc.effectiveness, rc.mapped_at as mapping_created_at
FROM risks r
JOIN risk_controls rc ON r.id = rc.risk_id
WHERE rc.control_id = $1
`

type ListControlRisksRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	InherentImpact     int32              `json:"inherent_impact"`
	InherentLikelihood int32              `json:"inherent_likelihood"`
	ResidualImpact     pgtype.Int4        `json:"residual_impact"`
	ResidualLikelihood pgtype.Int4        `json:"residual_likelihood"`
	Status             string             `json:"status"`
	TreatmentPlan      pgtype.Text        `json:"treatment_plan"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	SourceTaskID       pgtype.UUID        `json:"source_task_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Category           pgtype.Text        `json:"category"`
	ResponseStrategy   pgtype.Text        `json:"response_strategy"`
	MitigationPlan     pgtype.Text        `json:"mitigation_plan"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Notes              pgtype.Text        `json:"notes"`
	Effectiveness      pgtype.Text        `json:"effectiveness"`
	MappingCreatedAt   pgtype.Timestamptz `json:"mapping_created_at"`
}

func (q *Queries) ListControlRisks(ctx context.Context, controlID pgtype.UUID) ([]ListControlRisksRow, error) {
	rows, err := q.db.Query(ctx, listControlRisks, controlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlRisksRow
	for rows.Next() {
		var i ListControlRisksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.InherentImpact,
			&i.InherentLikelihood,
			&i.ResidualImpact,
			&i.ResidualLikelihood,
			&i.Status,
			&i.TreatmentPlan,
			&i.OwnerID,
			&i.SourceTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.ResponseStrategy,
			&i.MitigationPlan,
			&i.ReviewDate,
			&i.Notes,
			&i.Effectiveness,
			&i.MappingCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskControls = `-- name: ListRiskControls :many
SELECT risk_id, control_id, effectiveness, notes, mapped_at FROM risk_controls WHERE risk_id = $1
`

func (q *Queries) ListRiskControls(ctx context.Context, riskID pgtype.UUID) ([]RiskControl, error) {
	rows, err := q.db.Query(ctx, listRiskControls, riskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskControl
	for rows.Next() {
		var i RiskControl
		if err := rows.Scan(
			&i.RiskID,
			&i.ControlID,
			&i.Effectiveness,
			&i.Notes,
			&i.MappedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksByOrg = `-- name: ListRisksByOrg :many
SELECT id, org_id, title, description, inherent_impact, inherent_likelihood, residual_impact, residual_likelihood, status, treatment_plan, owner_id, source_task_id, created_at, updated_at, category, response_strategy, mitigation_plan, review_date FROM risks
WHERE org_id = $1
ORDER BY inherent_impact * inherent_likelihood DESC, created_at DESC
`

func (q *Queries) ListRisksByOrg(ctx context.Context, orgID pgtype.UUID) ([]Risk, error) {
	rows, err := q.db.Query(ctx, listRisksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.InherentImpact,
			&i.InherentLikelihood,
			&i.ResidualImpact,
			&i.ResidualLikelihood,
			&i.Status,
			&i.TreatmentPlan,
			&i.OwnerID,
			&i.SourceTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.ResponseStrategy,
			&i.MitigationPlan,
			&i.ReviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRisk = `-- name: UpdateRisk :one
UPDATE risks
SET 
    title = $2,
    description = $3,
    inherent_impact = $4,
    inherent_likelihood = $5,
    residual_impact = $6,
    residual_likelihood = $7,
    status = $8,
    treatment_plan = $9,
    owner_id = $10,
    category = $11,
    response_strategy = $12,
    mitigation_plan = $13,
    review_date = $14,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, title, description, inherent_impact, inherent_likelihood, residual_impact, residual_likelihood, status, treatment_plan, owner_id, source_task_id, created_at, updated_at, category, response_strategy, mitigation_plan, review_date
`

type UpdateRiskParams struct {
	ID                 pgtype.UUID `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	InherentImpact     int32       `json:"inherent_impact"`
	InherentLikelihood int32       `json:"inherent_likelihood"`
	ResidualImpact     pgtype.Int4 `json:"residual_impact"`
	ResidualLikelihood pgtype.Int4 `json:"residual_likelihood"`
	Status             string      `json:"status"`
	TreatmentPlan      pgtype.Text `json:"treatment_plan"`
	OwnerID            pgtype.UUID `json:"owner_id"`
	Category           pgtype.Text `json:"category"`
	ResponseStrategy   pgtype.Text `json:"response_strategy"`
	MitigationPlan     pgtype.Text `json:"mitigation_plan"`
	ReviewDate         pgtype.Date `json:"review_date"`
}

func (q *Queries) UpdateRisk(ctx context.Context, arg UpdateRiskParams) (Risk, error) {
	row := q.db.QueryRow(ctx, updateRisk,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.InherentImpact,
		arg.InherentLikelihood,
		arg.ResidualImpact,
		arg.ResidualLikelihood,
		arg.Status,
		arg.TreatmentPlan,
		arg.OwnerID,
		arg.Category,
		arg.ResponseStrategy,
		arg.MitigationPlan,
		arg.ReviewDate,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.InherentImpact,
		&i.InherentLikelihood,
		&i.ResidualImpact,
		&i.ResidualLikelihood,
		&i.Status,
		&i.TreatmentPlan,
		&i.OwnerID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.ResponseStrategy,
		&i.MitigationPlan,
		&i.ReviewDate,
	)
	return i, err
}
