// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_config.sql

package db

import (
	"context"
)

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT key, value, created_at, updated_at FROM system_config WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSystemConfig(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getSystemConfig, key)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSystemConfig = `-- name: SetSystemConfig :one
INSERT INTO system_config (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = CURRENT_TIMESTAMP
RETURNING key, value, created_at, updated_at
`

type SetSystemConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, setSystemConfig, arg.Key, arg.Value)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
