// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTaskActors = `-- name: AssignTaskActors :one
UPDATE tasks
SET 
    owner_id = $2,
    reviewer_id = $3,
    assessor_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, program_id, control_id, asset_id, owner_id, reviewer_id, assessor_id, title, description, status, result, due_date, created_at, updated_at, org_id, notes, reviewer_notes, assessor_notes, visible_to_assignee, task_type, evidence_required
`

type AssignTaskActorsParams struct {
	ID         pgtype.UUID `json:"id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
	AssessorID pgtype.UUID `json:"assessor_id"`
}

func (q *Queries) AssignTaskActors(ctx context.Context, arg AssignTaskActorsParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTaskActors,
		arg.ID,
		arg.OwnerID,
		arg.ReviewerID,
		arg.AssessorID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ControlID,
		&i.AssetID,
		&i.OwnerID,
		&i.ReviewerID,
		&i.AssessorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Result,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.Notes,
		&i.ReviewerNotes,
		&i.AssessorNotes,
		&i.VisibleToAssignee,
		&i.TaskType,
		&i.EvidenceRequired,
	)
	return i, err
}

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO evidence (
    task_id, file_path, file_name, checksum, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, task_id, file_path, file_name, checksum, uploaded_by, uploaded_at
`

type CreateEvidenceParams struct {
	TaskID     pgtype.UUID `json:"task_id"`
	FilePath   string      `json:"file_path"`
	FileName   string      `json:"file_name"`
	Checksum   string      `json:"checksum"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, createEvidence,
		arg.TaskID,
		arg.FilePath,
		arg.FileName,
		arg.Checksum,
		arg.UploadedBy,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FilePath,
		&i.FileName,
		&i.Checksum,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    program_id, control_id, asset_id, owner_id, title, description, status, org_id, due_date, visible_to_assignee, task_type, evidence_required
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, program_id, control_id, asset_id, owner_id, reviewer_id, assessor_id, title, description, status, result, due_date, created_at, updated_at, org_id, notes, reviewer_notes, assessor_notes, visible_to_assignee, task_type, evidence_required
`

type CreateTaskParams struct {
	ProgramID         pgtype.UUID `json:"program_id"`
	ControlID         pgtype.UUID `json:"control_id"`
	AssetID           pgtype.UUID `json:"asset_id"`
	OwnerID           pgtype.UUID `json:"owner_id"`
	Title             string      `json:"title"`
	Description       pgtype.Text `json:"description"`
	Status            string      `json:"status"`
	OrgID             pgtype.UUID `json:"org_id"`
	DueDate           pgtype.Date `json:"due_date"`
	VisibleToAssignee pgtype.Bool `json:"visible_to_assignee"`
	TaskType          pgtype.Text `json:"task_type"`
	EvidenceRequired  []byte      `json:"evidence_required"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProgramID,
		arg.ControlID,
		arg.AssetID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.OrgID,
		arg.DueDate,
		arg.VisibleToAssignee,
		arg.TaskType,
		arg.EvidenceRequired,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ControlID,
		&i.AssetID,
		&i.OwnerID,
		&i.ReviewerID,
		&i.AssessorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Result,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.Notes,
		&i.ReviewerNotes,
		&i.AssessorNotes,
		&i.VisibleToAssignee,
		&i.TaskType,
		&i.EvidenceRequired,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, program_id, control_id, asset_id, owner_id, reviewer_id, assessor_id, title, description, status, result, due_date, created_at, updated_at, org_id, notes, reviewer_notes, assessor_notes, visible_to_assignee, task_type, evidence_required FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ControlID,
		&i.AssetID,
		&i.OwnerID,
		&i.ReviewerID,
		&i.AssessorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Result,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.Notes,
		&i.ReviewerNotes,
		&i.AssessorNotes,
		&i.VisibleToAssignee,
		&i.TaskType,
		&i.EvidenceRequired,
	)
	return i, err
}

const listEvidenceByTask = `-- name: ListEvidenceByTask :many
SELECT id, task_id, file_path, file_name, checksum, uploaded_by, uploaded_at FROM evidence
WHERE task_id = $1
`

func (q *Queries) ListEvidenceByTask(ctx context.Context, taskID pgtype.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FilePath,
			&i.FileName,
			&i.Checksum,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByOrg = `-- name: ListTasksByOrg :many
SELECT id, program_id, control_id, asset_id, owner_id, reviewer_id, assessor_id, title, description, status, result, due_date, created_at, updated_at, org_id, notes, reviewer_notes, assessor_notes, visible_to_assignee, task_type, evidence_required FROM tasks
WHERE org_id = $1
ORDER BY due_date ASC, created_at DESC
`

func (q *Queries) ListTasksByOrg(ctx context.Context, orgID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ControlID,
			&i.AssetID,
			&i.OwnerID,
			&i.ReviewerID,
			&i.AssessorID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Result,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.Notes,
			&i.ReviewerNotes,
			&i.AssessorNotes,
			&i.VisibleToAssignee,
			&i.TaskType,
			&i.EvidenceRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET 
    status = $2, 
    result = $3, 
    notes = $4,
    reviewer_notes = $5,
    assessor_notes = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, program_id, control_id, asset_id, owner_id, reviewer_id, assessor_id, title, description, status, result, due_date, created_at, updated_at, org_id, notes, reviewer_notes, assessor_notes, visible_to_assignee, task_type, evidence_required
`

type UpdateTaskStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	Result        pgtype.Text `json:"result"`
	Notes         pgtype.Text `json:"notes"`
	ReviewerNotes pgtype.Text `json:"reviewer_notes"`
	AssessorNotes pgtype.Text `json:"assessor_notes"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Notes,
		arg.ReviewerNotes,
		arg.AssessorNotes,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ControlID,
		&i.AssetID,
		&i.OwnerID,
		&i.ReviewerID,
		&i.AssessorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Result,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.Notes,
		&i.ReviewerNotes,
		&i.AssessorNotes,
		&i.VisibleToAssignee,
		&i.TaskType,
		&i.EvidenceRequired,
	)
	return i, err
}
