// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxonomy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO control_categories (
    org_id, name, description
) VALUES (
    $1, $2, $3
)
RETURNING id, org_id, name, description, created_at
`

type CreateCategoryParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ControlCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.OrgID, arg.Name, arg.Description)
	var i ControlCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO control_domains (
    org_id, name, description
) VALUES (
    $1, $2, $3
)
RETURNING id, org_id, name, description, created_at
`

type CreateDomainParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (ControlDomain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.OrgID, arg.Name, arg.Description)
	var i ControlDomain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, org_id, name, description, created_at FROM control_categories
WHERE org_id = $1 OR org_id IS NULL
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, orgID pgtype.UUID) ([]ControlCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlCategory
	for rows.Next() {
		var i ControlCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, org_id, name, description, created_at FROM control_domains
WHERE org_id = $1 OR org_id IS NULL
ORDER BY name
`

func (q *Queries) ListDomains(ctx context.Context, orgID pgtype.UUID) ([]ControlDomain, error) {
	rows, err := q.db.Query(ctx, listDomains, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlDomain
	for rows.Next() {
		var i ControlDomain
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
