// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, org_id, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	OrgID        pgtype.UUID `json:"org_id"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.OrgID,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const createUserWithVerification = `-- name: CreateUserWithVerification :one
INSERT INTO users (username, email, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at
`

type CreateUserWithVerificationParams struct {
	Username                   string             `json:"username"`
	Email                      string             `json:"email"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	PasswordHash               string             `json:"password_hash"`
	Role                       string             `json:"role"`
	EmailVerified              bool               `json:"email_verified"`
	VerificationToken          pgtype.Text        `json:"verification_token"`
	VerificationTokenExpiresAt pgtype.Timestamptz `json:"verification_token_expires_at"`
}

func (q *Queries) CreateUserWithVerification(ctx context.Context, arg CreateUserWithVerificationParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithVerification,
		arg.Username,
		arg.Email,
		arg.OrgID,
		arg.PasswordHash,
		arg.Role,
		arg.EmailVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users WHERE verification_token = $1 LIMIT 1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.OrgID,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at FROM users
WHERE org_id = $1
ORDER BY id
`

func (q *Queries) ListUsersByOrg(ctx context.Context, orgID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.OrgID,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVerificationToken = `-- name: UpdateVerificationToken :one
UPDATE users
SET verification_token = $1, verification_token_expires_at = $2
WHERE id = $3
RETURNING id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at
`

type UpdateVerificationTokenParams struct {
	VerificationToken          pgtype.Text        `json:"verification_token"`
	VerificationTokenExpiresAt pgtype.Timestamptz `json:"verification_token_expires_at"`
	ID                         int64              `json:"id"`
}

func (q *Queries) UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateVerificationToken, arg.VerificationToken, arg.VerificationTokenExpiresAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified = true, verification_token = NULL, verification_token_expires_at = NULL
WHERE verification_token = $1 AND verification_token_expires_at > NOW()
RETURNING id, username, email, created_at, org_id, password_hash, role, email_verified, verification_token, verification_token_expires_at
`

func (q *Queries) VerifyUserEmail(ctx context.Context, verificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
	)
	return i, err
}
